### ISSUE TITLE
OpenAPI Schema

### ISSUE THREAD

**Issue by dantagg** [FabmanHQ/fabman-api#2]
Do you have a URI for the Fabman API OpenAPI/SwaggerUI Schema? I'm trying to build a Python library to interface with the Fabman API and it would be good to be able to test it against a mocked API rather than your live API

**Comment by rluba** [comment]
Sure! You can get the Swagger schema from the same place [our Live API documentation](https://fabman.io/api/v1/documentation#/) gets it from: https://fabman.io/api/v1/swagger.json
