### ISSUE TITLE
Data to be parsed, format to POST to the API with bearer auth

### ISSUE THREAD

**Issue by Marcman80** [FabmanHQ/fabman-api#5]
Hello! I am currently working on integrating Fabman bridges to a maker space/the machines therein. 
We are attempting to add a custom (either Arduino or Pi) board with an RFID sensor for different hand-tool lockers that would require different levels of training. To avoid adding undue cost and using single relays and bridges for each equipment locker on top of the bridges we are already receiving for the score of machines, I was hoping to get your advice and expertise on the format/best devices and practice to send, retrieve and parse an RFID key and equipment authorization.  

Basically, I would love to know what sequence of events it would take in order to get values on whether or not a keycard holding member has training on certain equipment. I'm by no means a web developer, but I should be able to turn electromagnets on and off based on authorization once I figure out the correct steps to send requests and parse data from your wonderful API. Still early days in our integration. 

I'm thinking of using ArduinoJson library as of now, but want to know how many bytes I should reserve for each of the steps in this method. Would I have to run a Heartbeat loop and bridge configuration, or can it all be done with requests and a bearer auth to the HTTPS API? 

Appreciative and forever Tinkering,
Marc

**Comment by rluba** [comment]
Hey Marc!

I assume that’s solved because you saw [Roland’s post on our forum.](https://forum.fabman.io/t/tool-check-out-locker-integration/711/2?u=raphael)
I’m glad that it was helpful!
